CDVICE=0

NUM_LAYERS=3
BATCH_SIZE=15
NUM_CLASSES=27288
NUM_CLASSES_ACT=43
ATTENTION_OPTION=conv

SCRIPT_FILE=/n/sd3/feng/ASR/exercise/trung/data/swda_seg_full_vocab_old_split20_train.csv

SAVE_DIR=DA_model
MODEL_FILE=none

CUDA_VISIBLE_DEVICES=${CDVICE} python train-DA_joint_model.py ${NUM_LAYERS} ${BATCH_SIZE} ${NUM_CLASSES} ${NUM_CLASSES_ACT} ${ATTENTION_OPTION} ${SCRIPT_FILE} ${SAVE_DIR} ${MODEL_FILE}
